name: LeagueOfCrafters
authors: [AdamAguilera]
description: MOBA Plugin
version: 1.0
api-version: 1.17
main: bukkit.Main
commands:
  loc:
    description: This is LOC command
    usage: /loc <heroname>
